### ISSUE TITLE
Moteur de recherche

### ISSUE THREAD

**Issue by JBL034** [yesiman/ekoal.web.ekoalitos.fo.manaboost#8]
Connecter à http://open-library.cirad.fr/gsdm

déconnecter de open Lib, Alisea et Nitidae

**Ou alors remettre l'ancien moteur de recherche sans Bowl. Plus simple sans doute...**

**Comment by yesiman** [comment]
Presque, il faut encore que j'attribue a manaboost les catégories manquantes.
